// Define your controller and the objects you need to reference.
netApp.controller('videosController', function ($scope) {
 	$scope.videos = [
    {
      id:1,
      name: 'Bob Burnquist built a floating miniramp in the middle of Lake Tahoe',
      description: "###*Is this video FTW? Rank it above.* BMX rider Andy Buckworth didn't make it all the way to [Nitro Circus][1] by being careful. Buckworth has pushed things on a bike since he was just a little kid in Australia. In this Rare Air interview on *[Crooked World BMX][2]*, Buckworth talks about his first jump he ever built, which was made from a sewer grate and two bricks and sat at the end of a very huge hill. ###*What do you think of this episode of* Crooked World BMX*? Tell us in the Comments.* [1]: http://www.networka.com/tags/1498/nitro-circus [2]: http://www.networka.com/shows/10/crooked-world-bmx",
      short_description: 'Boot toot',
      meta_description: null,
      meta_title: null,
      slug: "cuando-debe-ser-desconectado-un-paciente-con-muerte-cerebral-primer-impacto",
    
      provider: "YouTube",
      provider_uid: "R0KFSbcy-oc",
    
      comments_count: 1,
      views_count: 2345,
      
      picture_id:1,
    
      created_at: "2014-03-17T15:42:14.230Z",
      updated_at: "2014-03-17T15:47:46.309Z",
      uploaded_at: "2014-01-15T06:14:20.000Z",
      published_at: "2014-03-17T15:47:46.305Z",
      status: "published",
    },
    {
      id:2,
      name: 'Watch a snowboarder get towed by an electric jet engine at 50 miles per hour',
      description: "BMX riders are resourceful people. And they also like to party. For St. Patrick's Day, *[Crooked World BMX][1]* invited pro riders Albert Mercado, Hoang Tran, Dirt Ron, Kyle Hart, Demarcus Paul, and Tom Perry to enjoy a couple beers and have a miniramp jam. Rather than just popping bottles the traditional way, these BMX riders discovered that their bikes also make outstanding bottle openers. This is the best St. Patrick's Day BMX video you will ever see. Happy St. Paddy's Day! *What do you think of this episode of Crooked World BMX? Tell us in the Comments.* [1]: http://www.networka.com/shows/10/crooked-world-bmx",
      short_description: 'Scoot scoot!',
      meta_description: null,
      meta_title: null,
      slug: "bmx-riders-use-moving-bikes-to-open-beer-bottles-on-crooked-world",
    
      provider: "YouTube",
      provider_uid: "XkoNrHQ02qQ",
    
      comments_count: 13,
      views_count: 41504,
      
      picture_id:2,
    
      created_at: "2014-03-12T19:55:43.989Z",
      updated_at: "2014-03-19T15:15:46.401Z",
      uploaded_at: "2014-01-15T06:14:20.000Z",
      published_at: "2014-03-17T15:47:46.305Z",
      status: "published",
    },
    {
      id:3,
      name: "Dose: Jefferson Pang celebrates 20 years of skateboarding with an awesome Shut deck",
      description: "###*Do you think this video is FTW? Rank it above.* ↵↵[New York City's][1] first professional street skater [Jefferson Pang][2] has seen [just about everything][3] in his 20-plus years in skateboarding. On the new episode of *[Dose][4]* Pang drops some OG knowledge and gives a history lesson on the three NYC skaters that everyone should know about: [Beasley][5], [Jeremy Henderson][6], and [Harry Jumanji][7]. Pang also shows off his newly released pro model deck with [Shut Skateboards][8] to celebrate his skate legacy.↵↵To purchase Jefferson Pang's new Shut skateboard deck, [go to ShutNYC.com.][9] ↵↵###*What do you think of Jefferson Pang's new Shut skateboard? Tell us in the Comments.* ↵↵  [1]: http://www.networka.com/tags/347/new-york-city↵  [2]: http://www.networka.com/tags/1305/jefferson-pang↵  [3]: http://www.shutnyc.com/page/news/id/619/t/shut-jeff-pang-first-things-first/↵  [4]: http://www.networka.com/shows/9/dose↵  [5]: http://www.youtube.com/watch?v=G0r1qpt_V7U↵  [6]: http://www.youtube.com/watch?v=mIqqJQoHypo↵  [7]: http://www.youtube.com/watch?v=CXiSWs72qf4↵  [8]: http://www.networka.com/tags/4645/shut-skateboards↵  [9]: http://www.shutnyc.com/page/shop/id/621/t/shut-pang-deck/",
      short_description: 'I don\'t even know what to say',
      meta_description: null,
      meta_title: null,
      slug: "jefferson-pang-talks-about-his-new-shut-skateboards-deck-on-dose",
    
      provider: "YouTube",
      provider_uid: "Vs1M-M8zDI0",
    
      comments_count: 1,
      views_count: 2345,
    
      picture_id:3,

      created_at: "2014-03-18T18:37:14.054Z",
      updated_at: "2014-03-17T15:47:46.309Z",
      uploaded_at: "2014-01-15T06:14:20.000Z",
      published_at: "2014-03-18T20:43:04.913Z",
      status: "published",
    },
    {
      id:4,
      name: 'Fan Friday: BMX rider Alfred "Rat Boy" Cojocariu rips at local DIY park',
      description: 'Más noticias: http://bit.ly/10W33sR Dos nuevos casos avivaron la polémica y el Dr. Juan Rivera aclaró cuándo es posible desconectarlos y cuándo no. SUSCRIBETE!: http://www.youtube.com/channel/UC9SUMV0oYm0XK9H-c3GmKaQ Primer Impacto: Encuentra las noticias y reportajes más impactantes que ocurren en Estados Unidos y el mundo, presentadas por Bárbara Bermudo y Pamela Silva-Conde. Síguenos en Twitter: http://bit.ly/ZhUzJU Síguenos en Facebook: http://on.fb.me/16NsW0D Más noticias en: http://noticias.univision.com ¿Cuándo debe ser desconectado un paciente con muerte cerebral? - Primer Impacto ',
      short_description: 'Wow what the heck',
      meta_description: null,
      meta_title: null,
      slug: "cuando-debe-ser-desconectado-un-paciente-con-muerte-cerebral-primer-impacto",
    
      provider: "YouTube",
      provider_uid: "R0KFSbcy-oc",
    
      comments_count: 1,
      views_count: 2345,
      
      picture_id:4,
    
      created_at: "2014-03-17T15:42:14.230Z",
      updated_at: "2014-03-17T15:47:46.309Z",
      uploaded_at: "2014-01-15T06:14:20.000Z",
      published_at: "2014-03-17T15:47:46.305Z",
      status: "published",
    }
  ];

});

netApp.controller('reactionsController', function ($scope) {
  $scope.reactions = [
    {
    type: "react",
    id: 14700,
    reaction_id: 2,
    updated_at: "2014-04-25T22:00:30.405Z",
    created_at: "2014-04-25T22:00:30.405Z",
    participant: {
    id: 59,
    name: "Ben Slepp",
    name_first: "Ben",
    name_last: "Slepp",
    facebook_id: "506346731"
    },
    actionable: {
    type: "video",
    id: 30636,
    type_name: "video",
    created_at: "2014-04-24T15:55:50.882Z",
    duration: "35.0",
    updated_at: "2014-04-25T22:00:30.499Z",
    name: "How NOT to do feeble grinds on a BMX bike",
    long_name: null,
    short_description: "Your T-shirt shouldn't rip",
    meta_description: "BMX rider Max Eyre tried a feeble grind BMX trick but fell over his handlebars and slammed in an epic fail.",
    meta_title: "BMX rider Max Eyre feeble grind fail",
    original: null,
    status: "published",
    uploaded_at: "2014-04-22T21:42:07.000Z",
    published_at: "2014-04-24T21:30:00.000Z",
    publishing_sequence: "1398375000.000000",
    featured: false,
    featured_at: null,
    slug: "bmx-rider-max-eyre-feeble-grind-fail",
    attribution_id: 1300,
    sponsor_id: null,
    picture_id: 33380,
    provider: "YouTube",
    provider_description: "Max tries a Oppo Feeble opp hard on this ledge and then this happens...... #Fuckedup follow Me and him on instagram @_Max_Air and @Robbie_Brah and subscribe to his you tube account:Max Air https://www.youtube.com/user/MaxA7XAir like share and subscribe to my channel",
    provider_title: "Max Eyre | Feeble hard 180 ledge bail",
    provider_uid: "gC4ntvPz5xM",
    provider_url: "http://youtu.be/gC4ntvPz5xM",
    show_episode: null,
    show_id: null,
    show_season: null,
    action_participations_count: 12,
    comments_count: 63,
    views_count: 144379,
    react_actions_counts: {
    1: "1",
    2: "2",
    3: "1",
    4: "2",
    5: "3",
    7: "1"
    }
    }
    },
    {
    type: "react",
    id: 14699,
    reaction_id: 5,
    updated_at: "2014-04-25T22:00:29.208Z",
    created_at: "2014-04-25T22:00:29.208Z",
    participant: {
    id: 59,
    name: "Ben Slepp",
    name_first: "Ben",
    name_last: "Slepp",
    facebook_id: "506346731"
    },
    actionable: {
    type: "video",
    id: 30636,
    type_name: "video",
    created_at: "2014-04-24T15:55:50.882Z",
    duration: "35.0",
    updated_at: "2014-04-25T22:00:30.499Z",
    name: "How NOT to do feeble grinds on a BMX bike",
    long_name: null,
    short_description: "Your T-shirt shouldn't rip",
    meta_description: "BMX rider Max Eyre tried a feeble grind BMX trick but fell over his handlebars and slammed in an epic fail.",
    meta_title: "BMX rider Max Eyre feeble grind fail",
    original: null,
    status: "published",
    uploaded_at: "2014-04-22T21:42:07.000Z",
    published_at: "2014-04-24T21:30:00.000Z",
    publishing_sequence: "1398375000.000000",
    featured: false,
    featured_at: null,
    slug: "bmx-rider-max-eyre-feeble-grind-fail",
    attribution_id: 1300,
    sponsor_id: null,
    picture_id: 33380,
    provider: "YouTube",
    provider_description: "Max tries a Oppo Feeble opp hard on this ledge and then this happens...... #Fuckedup follow Me and him on instagram @_Max_Air and @Robbie_Brah and subscribe to his you tube account:Max Air https://www.youtube.com/user/MaxA7XAir like share and subscribe to my channel",
    provider_title: "Max Eyre | Feeble hard 180 ledge bail",
    provider_uid: "gC4ntvPz5xM",
    provider_url: "http://youtu.be/gC4ntvPz5xM",
    show_episode: null,
    show_id: null,
    show_season: null,
    action_participations_count: 12,
    comments_count: 63,
    views_count: 144379,
    react_actions_counts: {
    1: "1",
    2: "2",
    3: "1",
    4: "2",
    5: "3",
    7: "1"
    }
    }
    },
    {
    type: "react",
    id: 14698,
    reaction_id: 5,
    updated_at: "2014-04-25T21:29:48.380Z",
    created_at: "2014-04-25T21:29:48.380Z",
    participant: {
    id: 2991,
    name: "Gena Chernyshev",
    name_first: "Gena",
    name_last: "Chernyshev",
    facebook_id: "100000448101971"
    },
    actionable: {
    type: "video",
    id: 30707,
    type_name: "video",
    created_at: "2014-04-25T14:22:21.781Z",
    duration: "293.0",
    updated_at: "2014-04-25T21:29:48.576Z",
    name: "You won't believe how they changed the tires on this moving SUV",
    long_name: null,
    description: "###*Is this video WTF? Rank it.* Who needs a pit stop when you can just have the pit crew climb out of the car and change the tires while you're still driving on two wheels? That's what one intrepid group did in Saudi Arabia. The driver of a Toyota FJ Cruiser swerved to get the car up on its right-side wheels only. Then five passengers climbed out and changed the front and rear tires on the left side of of the SUV. This is next level ridiculous, and the driver deserves a medal for balancing the car on its side for such a long stretch. Seeing an Toyota FJ Cruiser driving on two wheels on a highway would be ridiculous enough in itself. But these guys from Saudi Arabia wanted next level ridiculous. Climbing out of the car while it's driving on two wheels, they proceed to change the front and rear tires on the passenger side. He's clearly much [more skilled than this guy.][1] ###*Is this the craziest tire change you've ever seen? Tell us in the Comments.* [1]: http://www.networka.com/videos/29759/driver-in-turkey-drives-like-maniac-listens-to-nelly",
    short_description: "What the hell just happened?",
    meta_description: "A driver in Saudi Arabia got his SUV on two wheels and then passengers changed the two other tires while the car was moving.",
    meta_title: "Tire change while driving on two wheels in Saudi Arabia",
    original: null,
    status: "published",
    uploaded_at: "2014-03-31T18:40:54.000Z",
    published_at: "2014-04-25T18:00:00.000Z",
    publishing_sequence: "1398448800.000000",
    featured: false,
    featured_at: null,
    slug: "tire-change-while-driving-on-two-wheels-in-saudi-arabia",
    attribution_id: 1305,
    sponsor_id: null,
    picture_id: 33480,
    provider: "YouTube",
    provider_description: "Saudis changing Wheels/ tyres while driving on TOYOTA FJ CRUISER! Total Saudi MADNESS!",
    provider_title: "Saudi's Again Changing Wheels/Tyres while driving!",
    provider_uid: "MQm5BnhTBEQ",
    provider_url: "https://www.youtube.com/watch?v=MQm5BnhTBEQ",
    show_episode: null,
    show_id: null,
    show_season: null,
    action_participations_count: 6,
    comments_count: 441,
    views_count: 606848,
    react_actions_counts: {
    1: "1",
    2: "2",
    3: "1",
    5: "1",
    7: "1"
    }
    }
    },
    {
    type: "react",
    id: 14697,
    reaction_id: 3,
    updated_at: "2014-04-25T21:29:02.624Z",
    created_at: "2014-04-25T21:29:02.624Z",
    participant: {
    id: 2991,
    name: "Gena Chernyshev",
    name_first: "Gena",
    name_last: "Chernyshev",
    facebook_id: "100000448101971"
    },
    actionable: {
    type: "video",
    id: 30707,
    type_name: "video",
    created_at: "2014-04-25T14:22:21.781Z",
    duration: "293.0",
    updated_at: "2014-04-25T21:29:48.576Z",
    name: "You won't believe how they changed the tires on this moving SUV",
    long_name: null,
    description: "###*Is this video WTF? Rank it.* Who needs a pit stop when you can just have the pit crew climb out of the car and change the tires while you're still driving on two wheels? That's what one intrepid group did in Saudi Arabia. The driver of a Toyota FJ Cruiser swerved to get the car up on its right-side wheels only. Then five passengers climbed out and changed the front and rear tires on the left side of of the SUV. This is next level ridiculous, and the driver deserves a medal for balancing the car on its side for such a long stretch. Seeing an Toyota FJ Cruiser driving on two wheels on a highway would be ridiculous enough in itself. But these guys from Saudi Arabia wanted next level ridiculous. Climbing out of the car while it's driving on two wheels, they proceed to change the front and rear tires on the passenger side. He's clearly much [more skilled than this guy.][1] ###*Is this the craziest tire change you've ever seen? Tell us in the Comments.* [1]: http://www.networka.com/videos/29759/driver-in-turkey-drives-like-maniac-listens-to-nelly",
    short_description: "What the hell just happened?",
    meta_description: "A driver in Saudi Arabia got his SUV on two wheels and then passengers changed the two other tires while the car was moving.",
    meta_title: "Tire change while driving on two wheels in Saudi Arabia",
    original: null,
    status: "published",
    uploaded_at: "2014-03-31T18:40:54.000Z",
    published_at: "2014-04-25T18:00:00.000Z",
    publishing_sequence: "1398448800.000000",
    featured: false,
    featured_at: null,
    slug: "tire-change-while-driving-on-two-wheels-in-saudi-arabia",
    attribution_id: 1305,
    sponsor_id: null,
    picture_id: 33480,
    provider: "YouTube",
    provider_description: "Saudis changing Wheels/ tyres while driving on TOYOTA FJ CRUISER! Total Saudi MADNESS!",
    provider_title: "Saudi's Again Changing Wheels/Tyres while driving!",
    provider_uid: "MQm5BnhTBEQ",
    provider_url: "https://www.youtube.com/watch?v=MQm5BnhTBEQ",
    show_episode: null,
    show_id: null,
    show_season: null,
    action_participations_count: 6,
    comments_count: 441,
    views_count: 606848,
    react_actions_counts: {
    1: "1",
    2: "2",
    3: "1",
    5: "1",
    7: "1"
    }
    }
    },
    {
    type: "react",
    id: 14696,
    reaction_id: 1,
    updated_at: "2014-04-25T21:27:48.990Z",
    created_at: "2014-04-25T21:27:48.990Z",
    participant: {
    id: 2991,
    name: "Gena Chernyshev",
    name_first: "Gena",
    name_last: "Chernyshev",
    facebook_id: "100000448101971"
    },
    actionable: {
    type: "video",
    id: 30707,
    type_name: "video",
    created_at: "2014-04-25T14:22:21.781Z",
    duration: "293.0",
    updated_at: "2014-04-25T21:29:48.576Z",
    name: "You won't believe how they changed the tires on this moving SUV",
    long_name: null,
    description: "###*Is this video WTF? Rank it.* Who needs a pit stop when you can just have the pit crew climb out of the car and change the tires while you're still driving on two wheels? That's what one intrepid group did in Saudi Arabia. The driver of a Toyota FJ Cruiser swerved to get the car up on its right-side wheels only. Then five passengers climbed out and changed the front and rear tires on the left side of of the SUV. This is next level ridiculous, and the driver deserves a medal for balancing the car on its side for such a long stretch. Seeing an Toyota FJ Cruiser driving on two wheels on a highway would be ridiculous enough in itself. But these guys from Saudi Arabia wanted next level ridiculous. Climbing out of the car while it's driving on two wheels, they proceed to change the front and rear tires on the passenger side. He's clearly much [more skilled than this guy.][1] ###*Is this the craziest tire change you've ever seen? Tell us in the Comments.* [1]: http://www.networka.com/videos/29759/driver-in-turkey-drives-like-maniac-listens-to-nelly",
    short_description: "What the hell just happened?",
    meta_description: "A driver in Saudi Arabia got his SUV on two wheels and then passengers changed the two other tires while the car was moving.",
    meta_title: "Tire change while driving on two wheels in Saudi Arabia",
    original: null,
    status: "published",
    uploaded_at: "2014-03-31T18:40:54.000Z",
    published_at: "2014-04-25T18:00:00.000Z",
    publishing_sequence: "1398448800.000000",
    featured: false,
    featured_at: null,
    slug: "tire-change-while-driving-on-two-wheels-in-saudi-arabia",
    attribution_id: 1305,
    sponsor_id: null,
    picture_id: 33480,
    provider: "YouTube",
    provider_description: "Saudis changing Wheels/ tyres while driving on TOYOTA FJ CRUISER! Total Saudi MADNESS!",
    provider_title: "Saudi's Again Changing Wheels/Tyres while driving!",
    provider_uid: "MQm5BnhTBEQ",
    provider_url: "https://www.youtube.com/watch?v=MQm5BnhTBEQ",
    show_episode: null,
    show_id: null,
    show_season: null,
    action_participations_count: 6,
    comments_count: 441,
    views_count: 606848,
    react_actions_counts: {
    1: "1",
    2: "2",
    3: "1",
    5: "1",
    7: "1"
    }
    }
    },
    {
    type: "react",
    id: 14695,
    reaction_id: 7,
    updated_at: "2014-04-25T21:27:42.014Z",
    created_at: "2014-04-25T21:27:42.014Z",
    participant: {
    id: 2991,
    name: "Gena Chernyshev",
    name_first: "Gena",
    name_last: "Chernyshev",
    facebook_id: "100000448101971"
    },
    actionable: {
    type: "video",
    id: 30707,
    type_name: "video",
    created_at: "2014-04-25T14:22:21.781Z",
    duration: "293.0",
    updated_at: "2014-04-25T21:29:48.576Z",
    name: "You won't believe how they changed the tires on this moving SUV",
    long_name: null,
    description: "###*Is this video WTF? Rank it.* Who needs a pit stop when you can just have the pit crew climb out of the car and change the tires while you're still driving on two wheels? That's what one intrepid group did in Saudi Arabia. The driver of a Toyota FJ Cruiser swerved to get the car up on its right-side wheels only. Then five passengers climbed out and changed the front and rear tires on the left side of of the SUV. This is next level ridiculous, and the driver deserves a medal for balancing the car on its side for such a long stretch. Seeing an Toyota FJ Cruiser driving on two wheels on a highway would be ridiculous enough in itself. But these guys from Saudi Arabia wanted next level ridiculous. Climbing out of the car while it's driving on two wheels, they proceed to change the front and rear tires on the passenger side. He's clearly much [more skilled than this guy.][1] ###*Is this the craziest tire change you've ever seen? Tell us in the Comments.* [1]: http://www.networka.com/videos/29759/driver-in-turkey-drives-like-maniac-listens-to-nelly",
    short_description: "What the hell just happened?",
    meta_description: "A driver in Saudi Arabia got his SUV on two wheels and then passengers changed the two other tires while the car was moving.",
    meta_title: "Tire change while driving on two wheels in Saudi Arabia",
    original: null,
    status: "published",
    uploaded_at: "2014-03-31T18:40:54.000Z",
    published_at: "2014-04-25T18:00:00.000Z",
    publishing_sequence: "1398448800.000000",
    featured: false,
    featured_at: null,
    slug: "tire-change-while-driving-on-two-wheels-in-saudi-arabia",
    attribution_id: 1305,
    sponsor_id: null,
    picture_id: 33480,
    provider: "YouTube",
    provider_description: "Saudis changing Wheels/ tyres while driving on TOYOTA FJ CRUISER! Total Saudi MADNESS!",
    provider_title: "Saudi's Again Changing Wheels/Tyres while driving!",
    provider_uid: "MQm5BnhTBEQ",
    provider_url: "https://www.youtube.com/watch?v=MQm5BnhTBEQ",
    show_episode: null,
    show_id: null,
    show_season: null,
    action_participations_count: 6,
    comments_count: 441,
    views_count: 606848,
    react_actions_counts: {
    1: "1",
    2: "2",
    3: "1",
    5: "1",
    7: "1"
    }
    }
    },
    {
    type: "react",
    id: 14694,
    reaction_id: 2,
    updated_at: "2014-04-25T21:27:41.694Z",
    created_at: "2014-04-25T21:27:41.694Z",
    participant: {
    id: 2991,
    name: "Gena Chernyshev",
    name_first: "Gena",
    name_last: "Chernyshev",
    facebook_id: "100000448101971"
    },
    actionable: {
    type: "video",
    id: 30707,
    type_name: "video",
    created_at: "2014-04-25T14:22:21.781Z",
    duration: "293.0",
    updated_at: "2014-04-25T21:29:48.576Z",
    name: "You won't believe how they changed the tires on this moving SUV",
    long_name: null,
    description: "###*Is this video WTF? Rank it.* Who needs a pit stop when you can just have the pit crew climb out of the car and change the tires while you're still driving on two wheels? That's what one intrepid group did in Saudi Arabia. The driver of a Toyota FJ Cruiser swerved to get the car up on its right-side wheels only. Then five passengers climbed out and changed the front and rear tires on the left side of of the SUV. This is next level ridiculous, and the driver deserves a medal for balancing the car on its side for such a long stretch. Seeing an Toyota FJ Cruiser driving on two wheels on a highway would be ridiculous enough in itself. But these guys from Saudi Arabia wanted next level ridiculous. Climbing out of the car while it's driving on two wheels, they proceed to change the front and rear tires on the passenger side. He's clearly much [more skilled than this guy.][1] ###*Is this the craziest tire change you've ever seen? Tell us in the Comments.* [1]: http://www.networka.com/videos/29759/driver-in-turkey-drives-like-maniac-listens-to-nelly",
    short_description: "What the hell just happened?",
    meta_description: "A driver in Saudi Arabia got his SUV on two wheels and then passengers changed the two other tires while the car was moving.",
    meta_title: "Tire change while driving on two wheels in Saudi Arabia",
    original: null,
    status: "published",
    uploaded_at: "2014-03-31T18:40:54.000Z",
    published_at: "2014-04-25T18:00:00.000Z",
    publishing_sequence: "1398448800.000000",
    featured: false,
    featured_at: null,
    slug: "tire-change-while-driving-on-two-wheels-in-saudi-arabia",
    attribution_id: 1305,
    sponsor_id: null,
    picture_id: 33480,
    provider: "YouTube",
    provider_description: "Saudis changing Wheels/ tyres while driving on TOYOTA FJ CRUISER! Total Saudi MADNESS!",
    provider_title: "Saudi's Again Changing Wheels/Tyres while driving!",
    provider_uid: "MQm5BnhTBEQ",
    provider_url: "https://www.youtube.com/watch?v=MQm5BnhTBEQ",
    show_episode: null,
    show_id: null,
    show_season: null,
    action_participations_count: 6,
    comments_count: 441,
    views_count: 606848,
    react_actions_counts: {
    1: "1",
    2: "2",
    3: "1",
    5: "1",
    7: "1"
    }
    }
    },
    {
    type: "react",
    id: 14691,
    reaction_id: 2,
    updated_at: "2014-04-25T21:18:22.231Z",
    created_at: "2014-04-25T21:18:22.231Z",
    participant: {
    id: 3398,
    name: "Pedro de Riba",
    name_first: "Pedro",
    name_last: "de Riba",
    facebook_id: "100001468930417"
    },
    actionable: {
    type: "video",
    id: 29935,
    type_name: "video",
    created_at: "2014-04-22T21:45:36.579Z",
    duration: "140.0",
    updated_at: "2014-04-25T21:18:22.279Z",
    name: "Japanese snowboarders made a weird Rube Goldberg machine",
    long_name: null,
    description: "###*Is this video LOL? Rank it.* The snowboard scene in Japan is unique. When you're exposed to all those [weird game shows][1] and [strange goat-antelope hybrids][2], it has an effect on you. So seeing the [Japanese snowboard crew Wow][3] drop this video of a snowboard [Rube Goldberg machine][4] they built kinda makes sense. The snowboarders built their own version of the [board game Mouse Trap][5] and then spit fire, donned baseball uniforms, and rocked out on guitar. Why? Who knows. We're just glad it happened. ###*What do you think of this snowboard Rube Goldberg machine?* [1]: http://www.networka.com/videos/6779/a-japanese-game-show-about-drifting-is-as-awesome-as-it-sounds [2]: http://www.networka.com/videos/24792/snowboarders-scotty-lago-tim-humphreys-find-wild-kamoshika-in-japan [3]: http://www.weird92.com/ [4]: http://www.networka.com/videos/2772/beastie-boys-rube-goldberg-star-in-goldieblox-toy-commercial [5]: https://www.youtube.com/watch?v=wXTBqXNIqgo",
    short_description: "Dominos, anyone?",
    meta_description: "The Japanese snowboard crew Wow made a Rube Goldberg machine for snowboarding and then did some impressive snowboard tricks.",
    meta_title: "Japanese snowboarders make Rube Goldberg machine",
    original: null,
    status: "published",
    uploaded_at: "2014-04-09T17:51:36.000Z",
    published_at: "2014-04-25T16:30:00.000Z",
    publishing_sequence: "1398443400.000000",
    featured: false,
    featured_at: null,
    slug: "japanese-snowboarders-make-rube-goldberg-machine",
    attribution_id: 287,
    sponsor_id: null,
    picture_id: 33461,
    provider: "YouTube",
    provider_description: "The WOW Crew of Japan made the ultimate snowboarding Rube Goldberg Machine. Watch it.",
    provider_title: "WOW crazy snowboard contraption",
    provider_uid: "oDls_lQigiE",
    provider_url: "https://www.youtube.com/watch?v=oDls_lQigiE",
    show_episode: null,
    show_id: null,
    show_season: null,
    action_participations_count: 5,
    comments_count: 4,
    views_count: 22210,
    react_actions_counts: {
    2: "2"
    }
    }
    },
    {
    type: "react",
    id: 14689,
    reaction_id: 2,
    updated_at: "2014-04-25T21:16:35.610Z",
    created_at: "2014-04-25T21:16:35.610Z",
    participant: {
    id: 3398,
    name: "Pedro de Riba",
    name_first: "Pedro",
    name_last: "de Riba",
    facebook_id: "100001468930417"
    },
    actionable: {
    type: "video",
    id: 30649,
    type_name: "video",
    created_at: "2014-04-24T17:39:13.368Z",
    duration: "59.0",
    updated_at: "2014-04-25T21:16:35.761Z",
    name: "Skater lights himself on fire, bombs down a hill",
    long_name: null,
    description: "###*Is this video WTF? Rank it.* Skateboarder Brian Concannon isn't the type of guy who does things half-assed. So if he is going to bomb a hill, he's going to do it while he's set on fire. And if he's going to bomb a hill while ablaze, he's going to finish it off with a powerslide and a little shadowboxing before his friends put the flames out. Even with all those added levels of risk, Concannon's hill bomb still [ended better than this one.][1] ###*Is this the craziest hill bomb you've seen? Tell us in the Comments.* [1]: http://www.networka.com/videos/7934/bombing-hills-can-be-explosive",
    short_description: "Uh, ok.",
    meta_description: "Skateboarder Brian Concannon wanted to bomb a hill on a skateboard a little differently. So he bombed a hill on his skateboard while on fire.",
    meta_title: "Skateboarder bombs a hill while on fire",
    original: null,
    status: "published",
    uploaded_at: "2014-04-24T17:11:44.000Z",
    published_at: "2014-04-25T14:31:26.589Z",
    publishing_sequence: "1398436286.589000",
    featured: false,
    featured_at: null,
    slug: "skateboarder-bombs-a-hill-while-on-fire",
    attribution_id: 149,
    sponsor_id: null,
    picture_id: 33426,
    provider: "YouTube",
    provider_title: "JENKEM - WTF? Hill Bomb on Fire",
    provider_uid: "Stl67KNJIgw",
    provider_url: "http://www.youtube.com/watch?v=Stl67KNJIgw&feature=youtube_gdata_player",
    show_episode: null,
    show_id: null,
    show_season: null,
    action_participations_count: 3,
    comments_count: 1,
    views_count: 68,
    react_actions_counts: {
    2: "1"
    }
    }
    },
    {
    type: "react",
    id: 14687,
    reaction_id: 2,
    updated_at: "2014-04-25T21:13:29.072Z",
    created_at: "2014-04-25T21:13:29.072Z",
    participant: {
    id: 3398,
    name: "Pedro de Riba",
    name_first: "Pedro",
    name_last: "de Riba",
    facebook_id: "100001468930417"
    },
    actionable: {
    type: "video",
    id: 30707,
    type_name: "video",
    created_at: "2014-04-25T14:22:21.781Z",
    duration: "293.0",
    updated_at: "2014-04-25T21:29:48.576Z",
    name: "You won't believe how they changed the tires on this moving SUV",
    long_name: null,
    description: "###*Is this video WTF? Rank it.* Who needs a pit stop when you can just have the pit crew climb out of the car and change the tires while you're still driving on two wheels? That's what one intrepid group did in Saudi Arabia. The driver of a Toyota FJ Cruiser swerved to get the car up on its right-side wheels only. Then five passengers climbed out and changed the front and rear tires on the left side of of the SUV. This is next level ridiculous, and the driver deserves a medal for balancing the car on its side for such a long stretch. Seeing an Toyota FJ Cruiser driving on two wheels on a highway would be ridiculous enough in itself. But these guys from Saudi Arabia wanted next level ridiculous. Climbing out of the car while it's driving on two wheels, they proceed to change the front and rear tires on the passenger side. He's clearly much [more skilled than this guy.][1] ###*Is this the craziest tire change you've ever seen? Tell us in the Comments.* [1]: http://www.networka.com/videos/29759/driver-in-turkey-drives-like-maniac-listens-to-nelly",
    short_description: "What the hell just happened?",
    meta_description: "A driver in Saudi Arabia got his SUV on two wheels and then passengers changed the two other tires while the car was moving.",
    meta_title: "Tire change while driving on two wheels in Saudi Arabia",
    original: null,
    status: "published",
    uploaded_at: "2014-03-31T18:40:54.000Z",
    published_at: "2014-04-25T18:00:00.000Z",
    publishing_sequence: "1398448800.000000",
    featured: false,
    featured_at: null,
    slug: "tire-change-while-driving-on-two-wheels-in-saudi-arabia",
    attribution_id: 1305,
    sponsor_id: null,
    picture_id: 33480,
    provider: "YouTube",
    provider_description: "Saudis changing Wheels/ tyres while driving on TOYOTA FJ CRUISER! Total Saudi MADNESS!",
    provider_title: "Saudi's Again Changing Wheels/Tyres while driving!",
    provider_uid: "MQm5BnhTBEQ",
    provider_url: "https://www.youtube.com/watch?v=MQm5BnhTBEQ",
    show_episode: null,
    show_id: null,
    show_season: null,
    action_participations_count: 6,
    comments_count: 441,
    views_count: 606848,
    react_actions_counts: {
    1: "1",
    2: "2",
    3: "1",
    5: "1",
    7: "1"
    }
    }
    },
    {
    type: "react",
    id: 14683,
    reaction_id: 2,
    updated_at: "2014-04-25T21:06:00.897Z",
    created_at: "2014-04-25T21:06:00.897Z",
    participant: {
    id: 2990,
    name: "Élie Desgreniers",
    name_first: "Élie",
    name_last: "Desgreniers",
    facebook_id: "100004739550586"
    },
    actionable: {
    type: "video",
    id: 29935,
    type_name: "video",
    created_at: "2014-04-22T21:45:36.579Z",
    duration: "140.0",
    updated_at: "2014-04-25T21:18:22.279Z",
    name: "Japanese snowboarders made a weird Rube Goldberg machine",
    long_name: null,
    description: "###*Is this video LOL? Rank it.* The snowboard scene in Japan is unique. When you're exposed to all those [weird game shows][1] and [strange goat-antelope hybrids][2], it has an effect on you. So seeing the [Japanese snowboard crew Wow][3] drop this video of a snowboard [Rube Goldberg machine][4] they built kinda makes sense. The snowboarders built their own version of the [board game Mouse Trap][5] and then spit fire, donned baseball uniforms, and rocked out on guitar. Why? Who knows. We're just glad it happened. ###*What do you think of this snowboard Rube Goldberg machine?* [1]: http://www.networka.com/videos/6779/a-japanese-game-show-about-drifting-is-as-awesome-as-it-sounds [2]: http://www.networka.com/videos/24792/snowboarders-scotty-lago-tim-humphreys-find-wild-kamoshika-in-japan [3]: http://www.weird92.com/ [4]: http://www.networka.com/videos/2772/beastie-boys-rube-goldberg-star-in-goldieblox-toy-commercial [5]: https://www.youtube.com/watch?v=wXTBqXNIqgo",
    short_description: "Dominos, anyone?",
    meta_description: "The Japanese snowboard crew Wow made a Rube Goldberg machine for snowboarding and then did some impressive snowboard tricks.",
    meta_title: "Japanese snowboarders make Rube Goldberg machine",
    original: null,
    status: "published",
    uploaded_at: "2014-04-09T17:51:36.000Z",
    published_at: "2014-04-25T16:30:00.000Z",
    publishing_sequence: "1398443400.000000",
    featured: false,
    featured_at: null,
    slug: "japanese-snowboarders-make-rube-goldberg-machine",
    attribution_id: 287,
    sponsor_id: null,
    picture_id: 33461,
    provider: "YouTube",
    provider_description: "The WOW Crew of Japan made the ultimate snowboarding Rube Goldberg Machine. Watch it.",
    provider_title: "WOW crazy snowboard contraption",
    provider_uid: "oDls_lQigiE",
    provider_url: "https://www.youtube.com/watch?v=oDls_lQigiE",
    show_episode: null,
    show_id: null,
    show_season: null,
    action_participations_count: 5,
    comments_count: 4,
    views_count: 22210,
    react_actions_counts: {
    2: "2"
    }
    }
    },
    {
    type: "react",
    id: 14671,
    reaction_id: 6,
    updated_at: "2014-04-25T19:05:33.968Z",
    created_at: "2014-04-25T19:05:33.968Z",
    participant: {
    id: 2083,
    name: "Nikos Tsitenidis",
    name_first: "Nikos",
    name_last: "Tsitenidis",
    facebook_id: "100001271191511"
    },
    actionable: {
    type: "video",
    id: 29759,
    type_name: "video",
    created_at: "2014-04-21T15:55:39.897Z",
    duration: "111.0",
    updated_at: "2014-04-25T19:27:30.467Z",
    name: "Driver weaves through traffic like a jerk while listening to Nelly",
    long_name: null,
    short_description: "People still listen to Nelly?",
    meta_title: "Driver in Turkey drives like maniac, listens to Nelly",
    original: null,
    status: "published",
    uploaded_at: "2014-03-23T04:22:30.000Z",
    published_at: "2014-04-22T14:32:50.251Z",
    publishing_sequence: "1398177170.251000",
    featured: false,
    featured_at: null,
    slug: "driver-in-turkey-drives-like-maniac-listens-to-nelly",
    attribution_id: 1201,
    sponsor_id: null,
    picture_id: 32466,
    provider: "YouTube",
    provider_description: "",
    provider_title: "Audi A3 3.2 V6 Quattro Turkey-İstanbul",
    provider_uid: "Jjxrxu3aDvk",
    provider_url: "http://youtu.be/Jjxrxu3aDvk",
    show_episode: null,
    show_id: null,
    show_season: null,
    action_participations_count: 14,
    comments_count: 102,
    views_count: 61989,
    react_actions_counts: {
    2: "2",
    3: "1",
    5: "1",
    6: "2"
    }
    }
    },
    {
    type: "react",
    id: 14667,
    reaction_id: 7,
    updated_at: "2014-04-25T19:04:36.644Z",
    created_at: "2014-04-25T19:04:36.644Z",
    participant: {
    id: 2083,
    name: "Nikos Tsitenidis",
    name_first: "Nikos",
    name_last: "Tsitenidis",
    facebook_id: "100001271191511"
    },
    actionable: {
    type: "video",
    id: 29903,
    type_name: "video",
    created_at: "2014-04-22T19:50:49.509Z",
    duration: "24.0",
    updated_at: "2014-04-25T19:04:36.711Z",
    name: "Tank does donuts amid armed conflict in Ukraine",
    long_name: null,
    description: "###*Is this video WTF? Rank it.* The situation in Ukraine right now is not good. That is putting things mildly. Tensions are running high in the armed conflict between pro-Russia and opposition forces. Still, there was a brief moment of levity in the eastern Ukranian city of Sloviansk. A tank belonging to pro-Russian forces decided to do some donuts before speeding away. Wonder if that tank driver needed [a push-button line lock feature][1]. ###*What do you think of this tank burnout? Tell us in the Comments.* [1]: http://www.networka.com/videos/29773/2015-ford-mustang-gt-has-line-lock-feature-for-burnouts",
    short_description: "WTF?",
    meta_description: "A tank belonging to pro-Russia forces in the city of Sloviansk in eastern Ukraine did donuts and a burnout before speeding off amid the armed conflict.",
    meta_title: "Tank does donuts amid armed conflict in Ukraine",
    original: null,
    status: "published",
    uploaded_at: "2014-04-16T09:11:26.000Z",
    published_at: "2014-04-23T16:36:45.976Z",
    publishing_sequence: "1398271005.976000",
    featured: false,
    featured_at: null,
    slug: "tank-does-donuts-amid-armed-conflict-in-ukraine",
    attribution_id: 1216,
    sponsor_id: null,
    picture_id: 32950,
    provider: "YouTube",
    provider_description: "Anti-Kiev, pro-Russia tanks entertain the crowd before leaving.",
    provider_title: "Sloviansk - Tanks (APCs) Doing Show-tricks - April 16th",
    provider_uid: "6bpabV3S4uA",
    provider_url: "http://youtu.be/6bpabV3S4uA",
    show_episode: null,
    show_id: null,
    show_season: null,
    action_participations_count: 6,
    comments_count: 2502,
    views_count: 965823,
    react_actions_counts: {
    7: "1"
    }
    }
    },
    {
    type: "react",
    id: 14664,
    reaction_id: 5,
    updated_at: "2014-04-25T19:03:43.348Z",
    created_at: "2014-04-25T19:03:43.348Z",
    participant: {
    id: 2083,
    name: "Nikos Tsitenidis",
    name_first: "Nikos",
    name_last: "Tsitenidis",
    facebook_id: "100001271191511"
    },
    actionable: {
    type: "video",
    id: 29626,
    type_name: "video",
    created_at: "2014-04-18T14:33:30.605Z",
    duration: "63.0",
    updated_at: "2014-04-25T19:03:43.463Z",
    name: "Drifting with only one hand on the steering wheel is no problem for this guy",
    long_name: null,
    description: "###*Is this video Holy? Rank it.* Drifting takes two hands, there is no doubt about that. Shifting and pulling the e-brake require your right hand (or left if you're weird on drive on the other side of the road). Steering requires your left hand. And even a professional like Chris Forsberg will [put his right hand on the steering wheel][1] going through a hard turn. It's just the nature of it, and putting both hands on the wheel at times are completely necessary. Not so for Niculae Dobre though. Dobre is from Romania and clearly an underground badass. During this entire tandem with a fellow drifter Dobre does not once put his right hand on the wheel. Taking these hard turns with only one hand is unfathomable, and we're still scratching our heads as to how he does this in his V-8 BMW E30. ###*Have you ever seen anyone else drift with only one hand on the steering wheel? Tell us in the Comments.* [1]: http://www.networka.com/videos/28428/drift-with-chris-forsberg-at-formula-drift-long-beach",
    short_description: "His name is Niculae Dobre",
    meta_description: "Romanian drifter Niculae Dobre can drift during tandem with only one hand on the steering wheel. He might be the maddest of them all.",
    meta_title: "Drifter Niculae Dobre only uses one hand to drift",
    original: null,
    status: "published",
    uploaded_at: "2014-03-17T21:07:03.000Z",
    published_at: "2014-04-18T19:22:17.598Z",
    publishing_sequence: "1397848937.598000",
    featured: false,
    featured_at: null,
    slug: "drifter-niculae-dobre-only-uses-one-hand-to-drift",
    attribution_id: 641,
    sponsor_id: null,
    picture_id: 32223,
    provider: "YouTube",
    provider_description: "You just know there's something special with this guy from the moment you see him driving. The levels of commitment and involvement are absolutely off the chart! His name is Dobre, his car is a V8 powered BMW E30, and he drifts using just one hand! Oh, and we were in the middle of a tandem with Marius KNS the whole time! Uber cool! More drifting news,videos and photos can be seen on : www.facebook.com/drift.ro Please subscribe to the channel and also like our Facebook page! http://www.youtube.com/user/driftshorts",
    provider_title: "Drift.ro Shorts: Onboard drifting with a madman",
    provider_uid: "CiFc82GZgLk",
    provider_url: "https://www.youtube.com/watch?v=CiFc82GZgLk&feature=youtu.be",
    show_episode: null,
    show_id: null,
    show_season: null,
    action_participations_count: 14,
    comments_count: 2,
    views_count: 2078,
    react_actions_counts: {
    3: "2",
    5: "1"
    }
    }
    },
    {
    type: "react",
    id: 14658,
    reaction_id: 7,
    updated_at: "2014-04-25T17:38:31.130Z",
    created_at: "2014-04-25T17:38:31.130Z",
    participant: {
    id: 3141,
    name: "Robbie Fader",
    name_first: "Robbie",
    name_last: "Fader",
    facebook_id: "1288956149"
    },
    actionable: {
    type: "video",
    id: 29811,
    type_name: "video",
    created_at: "2014-04-22T01:12:53.066Z",
    duration: "212.0",
    updated_at: "2014-04-25T17:38:31.216Z",
    name: "Chuck Aaron's helicopter stunts are almost as cool as his mustache",
    long_name: null,
    short_description: "It's close",
    meta_title: "Helicopter pilot Chuck Aaron does aerobatic flying stunts",
    original: null,
    status: "published",
    uploaded_at: "2014-04-21T23:31:09.000Z",
    published_at: "2014-04-25T13:00:00.000Z",
    publishing_sequence: "1398430800.000000",
    featured: false,
    featured_at: null,
    slug: "helicopter-pilot-chuck-aaron-does-aerobatic-flying-stunts",
    attribution_id: 24,
    sponsor_id: null,
    picture_id: 33412,
    provider: "YouTube",
    provider_title: "Aerobatic helicopter tricks with Chuck Aaron",
    provider_uid: "mQT26oxOG4c",
    provider_url: "http://www.youtube.com/watch?v=mQT26oxOG4c&feature=youtube_gdata_player",
    show_episode: null,
    show_id: null,
    show_season: null,
    action_participations_count: 2,
    comments_count: 100,
    views_count: 301,
    react_actions_counts: {
    1: "1",
    7: "1"
    }
    }
    }
  ]
  
  $scope.clusterReactions = function() {
    $scope.clusteredActions = [];
    $scope.userIds = [];
    
    angular.forEach($scope.reactions, function(reaction, key) {
      if (!(reaction.participant.id in $scope.userIds)) {
        $scope.userIds[reaction.participant.id] = {id: reaction.participant.id, name:reaction.participant.name, reactions: []};
        $scope.clusteredActions.push($scope.userIds[reaction.participant.id]);
      }
      $scope.userIds[reaction.participant.id].reactions.push(reaction.reaction_id);
    } );
    
    console.log ($scope.userIds);
    
  }
  
  $scope.clusterReactions();
});